config/routes.rb
E4th::Application.routes.draw do
  resources :users  do
    collection { post :import }
  end

  resources :docs do
    get :download
  end
  
  resources :microposts do
    get :download
    get :download_max
    get :download_small
  end  

  resources :images do
    get :download
    get :download_max
    get :download_small
  end

  resources :articles
  resources :sessions,      only: [:new, :create, :destroy]
  
  root  'static_pages#home'
  match '/find',        to: 'users#find',               via: 'get'
  match '/csv',         to: 'users#csv',                via: 'get'
  match '/signup',      to: 'users#new',                via: 'get'
  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'
  match '/help',        to: 'static_pages#help',        via: 'get'
  match '/about',       to: 'static_pages#about',       via: 'get'

end

app/models/article.rb
# encoding: utf-8

class Article < ActiveRecord::Base
  has_many :images
  has_many :pictures
  validates :title, presence: true

end

app/controllers/articles_controller.rb
# encoding: utf-8

class ArticlesController < ApplicationController
  before_action :signed_in_user,
                only: [:index, :show, :edit, :update, :destroy]

  def show
    @article = Article.find(params[:id])
    @picture = @article.pictures.build
    @pictures = @article.pictures.paginate(page: params[:page], per_page: 5)
    @image = @article.images.build
    @images = @article.images.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = "お知らせが登録されました!"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      flash[:success] = "お知らせは更新されました！"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def index
    #@articles = Article.all
    @articles = Article.where(group_id: current_user.group_id).order("created_at DESC")
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "お知らせは削除されました！"
    redirect_to articles_url
  end
    
  private
    # Never trust parameters from the scary internet, only allow the white
    # list through.
    def article_params
      params.require(:article).permit(:title, 
                                      :group_id,
                                      :user_id,
                                      :date,
                                      :content)
    end  

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "サインインしてください"
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<% provide(:title, 'お知らせ更新') %>
<article id="contents">
<header class="head">
<h1>お知らせ更新</h1>
</header>
<div class="main">

<section class="form">
  <%= form_for(@article) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <dl class="formList">
      <dt><%= f.label :title, "題名" %></dt>
      <dd><%= f.text_field :title %></dd>

      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :group_id, :value => current_user.group_id %>

      <dt><%= f.label :content, "内容" %></dt>
      <dd><%= f.text_area :content, rows: 6 %><dd>
    </dl>
    <p><%= f.submit "お知らせ更新", class: "commonSubmit" %></p>
  <% end %>
</section>

</div>
</article>

app/views/articles/index.html.erb
<% provide(:title, 'お知らせ一覧') %>
<article id="contents">
<header class="head">
<h1>お知らせ一覧</h1>
</header>
<div class="main">

<div id="articleList">
<ul >
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
      <% if current_user?(article.user_id) || current_user.admin? %>
        | <%= link_to "Edit", edit_article_path(article) %>
      <% end %>
      <% if current_user.admin? %>
        | <%= link_to "Delete", article, method: :delete,
                                 data: { confirm: "本当に削除しますか?" } %>
      <% end %>
    </li>
  <% end %>
</ul>
</div>

</div>
</article>

app/views/articles/new.html.erb
<% provide(:title, 'お知らせ登録') %>
<article id="contents">
<header class="head">
<h1>お知らせ登録</h1>
</header>
<div class="main">

<section class="form">
  <%= form_for(@article) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <dl class="formList">
      <dt><%= f.label :title, "題名" %></dt>
      <dd><%= f.text_field :title %></dd>

      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :group_id, :value => current_user.group_id %>

      <dt><%= f.label :content, "内容" %></dt>
      <dd><%= f.text_area :content, rows: 6 %><dd>
     </dl>
     <p><%= f.submit "お知らせ登録", class: "commonSubmit" %></p>
  <% end %>
</section>

</div>
</article>

app/views/articles/show.html.erb
<% provide(:title, 'お知らせ') %>
<article id="contents">
<header class="head">
<h1><%= @article.title %></h1>
</header>
<div class="main">

<div id="articleArea">
<section class="content">
<%= markdown(@article.content) %>
</section>
<%= will_paginate @images, previous_label: "前ページ", next_label: "次ページ" %>
  <% if @article.images.count > 0 %>
  <div id="pictureList">
    <% @images.each do |pic| %>
      <% if pic.name != nil %>
      <article>
        <section>
          <%= pic.name %> | <%= pic.user.name %> 
          <% if (current_user.admin? || current_user.id == pic.user_id) %>
             | <%= link_to "削除", pic, method: :delete,
                                 data: { confirm: "本当に削除しますか?" } %>

          <% end %>
          <p><a href="<%= image_path(pic) %>"><img src="<%= image_download_path(pic) %>"></a></p>
        </section>
      </article>
      <% end %>
    <% end %>
  </div>
  <% end %>
<%= will_paginate  @images, previous_label: "前ページ", next_label: "次ページ" %>
<% if current_user.family != "GUEST" %>
  <section class="form">
  <%= form_for(@image,
                html: {multipart: true}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <dl class="formList">
      <%= f.hidden_field :article_id, :value => @article.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <dd><%= f.file_field :uploaded_image %></dd>
    </dl>
    <p><%= f.submit "写真追加", class: "btn btn-normal btn-primary" %></p>
  <% end %>
  </section>
<% end %>
</div>
</div>
</article>