config/routes.rb
E4th::Application.routes.draw do
  resources :users  do
    collection { post :import }
  end

  resources :docs do
    get :download
  end
  
  resources :microposts do
    get :download
    get :download_max
    get :download_small
  end  

  resources :images do
    get :download
    get :download_max
    get :download_small
  end

  resources :articles
  resources :sessions,      only: [:new, :create, :destroy]
  
  root  'static_pages#home'
  match '/find',        to: 'users#find',               via: 'get'
  match '/csv',         to: 'users#csv',                via: 'get'
  match '/signup',      to: 'users#new',                via: 'get'
  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'
  match '/help',        to: 'static_pages#help',        via: 'get'
  match '/about',       to: 'static_pages#about',       via: 'get'

end

app/models/doc.rb
# encoding: utf-8

class Doc < ActiveRecord::Base
  belongs_to :user
  validates :group_id, :user_id, :name, :description, presence: true

  def uploaded_doc=(doc_field)
    self.name     = base_part_of(doc_field.original_filename)
    self.doc_type = doc_field.content_type.chomp
    self.doc_data = doc_field.read
  end

  def base_part_of(file_name)
#    File.basename(file_name).gsub(/[\A\w._-]/, '')
    File.basename(file_name)
  end

end

app/controllers/docs_controller.rb
# encoding: utf-8

class DocsController < ApplicationController
  before_action :signed_in_user, 
                only: [:index, :show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(group_id: current_user.group_id).order("created_at DESC")
            .paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @doc = Doc.new
  end

  def create
    #@doc = Doc.new(doc_params)
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      flash[:success] = "文書登録されました!"
      redirect_to @doc
    else
      render 'new'
    end
  end

  def download
    @doc = Doc.find(params[:doc_id])
    send_data(@doc.doc_data,
              filename: @doc.name,
              type: @doc.doc_type,
              disposition: "attachment")
  end

  def show
    @doc = Doc.find(params[:id])
  end

  def edit
    @doc = Doc.find(params[:id])
  end

  def update
    @doc = Doc.find(params[:id])
    if @doc.update_attributes(doc_params)
       flash[:success] = "文書更新されました!"
       redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    Doc.find(params[:id]).destroy
    flash[:success] = "文書削除されました!"
    redirect_to docs_url
  end
          
  private
    # Never trust parameters from the scary internet, only allow the white
    # list through.
    def doc_params
      params.require(:doc).permit(:group_id, 
                                  :user_id,
                                  :description,
                                  :uploaded_doc)
    end

    def correct_user
      @doc = current_user.docs.find_by(id: params[:id])
      redirect_to root_url if @doc.nil?
    end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_doc.html.erb
<li>
  <h3><%= doc.name %></h3>
  <span>
    <%= doc.user.name %>
      | <%= link_to "保存", doc_download_path(doc) %>
    <% if current_user?(doc.user) || current_user.admin? %>
      | <%= link_to "編集", edit_doc_path(doc) %>
      | <%= link_to "削除", doc, method: :delete,
                                   data: { confirm: "本当に削除しますか?" },
                                   title: doc.name %>
    <% end %>
  </span>

  <section>
    <p class='cf'>
      <%=markdown(doc.description) %>
    </p>
   </section>    
</li>

app/views/docs/edit.html.erb
<% provide(:title, '文書変更') %>
<article id="contents">
<header class="head">
<h1>文書変更</h1>
</header>
<div class="main">

<section class="form">
  <%= form_for(@doc, 
                html: {multipart: true}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <dl class="formList">
      <%= f.hidden_field :group_id, :value => current_user.group_id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>

      <dt><%= f.label :description, "内容" %></dt>
      <dd><%= f.text_area :description, rows: 6 %><dd>
<!--
      <dt><%= f.label :uploaded_doc, "文書選択" %></dt>
      <dd><%= f.file_field :uploaded_doc %></dd>
-->
    </dl>
    <p><%= f.submit "文書変更", class: "commonSubmit" %></p>
  <% end %>
</section>

</div>
</article>

app/views/docs/index.html.erb
<% provide(:title, '文書一覧') %>
<article id="contents">
<header class="head">
<h1>文書一覧</h1>
</header>
<div class="main">
<div id="docArea">
<%= will_paginate @docs, previous_label: "前ページ", next_label: "次ページ" %>
  <div id="docList">
  <ul>
  <%= render @docs %>
  </ul>
  </div>
<%= will_paginate @docs, previous_label: "前ページ", next_label: "次ページ" %>
</div>
</div>
</article>

app/views/docs/new.html.erb
<% provide(:title, '文書登録') %>
<article id="contents">
<header class="head">
<h1>文書登録</h1>
</header>
<div class="main">

<section class="form">
  <%= form_for(@doc, 
                html: {multipart: true}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <dl class="formList">
      <%= f.hidden_field :group_id, :value => current_user.group_id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>

      <dt><%= f.label :description, "内容" %></dt>
      <dd><%= f.text_area :description, rows: 6 %><dd>

      <dt><%= f.label :uploaded_doc, "文書選択" %></dt>
      <dd><%= f.file_field :uploaded_doc %></dd>
    </dl>
    <p><%= f.submit "文書登録", class: "commonSubmit" %></p>
  <% end %>
</section>

</div>
</article>

app/views/docs/show.html.erb
<% provide(:title, @doc.name) %>
<article id="contents">
<header class="head">
<h1><%= @doc.name %></h1>
</header>
<div class="main">

<div id="docArea">
<p><%= markdown(@doc.description) %></p>
</div>

</div>
</article>