config/routes.rb
E4th::Application.routes.draw do
  resources :users  do
    collection { post :import }
  end

  resources :docs do
    get :download
  end
  
  resources :microposts do
    get :download
    get :download_max
    get :download_small
  end  

  resources :images do
    get :download
    get :download_max
    get :download_small
  end

  resources :articles
  resources :sessions,      only: [:new, :create, :destroy]
  
  root  'static_pages#home'
  match '/find',        to: 'users#find',               via: 'get'
  match '/csv',         to: 'users#csv',                via: 'get'
  match '/signup',      to: 'users#new',                via: 'get'
  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'
  match '/help',        to: 'static_pages#help',        via: 'get'
  match '/about',       to: 'static_pages#about',       via: 'get'

end

app/models/micropost.rb
# encoding: utf-8

class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :group_id, presence: true
  validates :user_id, presence: true

  # 与えられたユーザーがフォローしているユーザー達のマイクロポストを返す。
#  def self.from_users_followed_by(user)
#    followed_user_ids = "SELECT followed_id FROM relationships
#                         WHERE follower_id = :user_id"
#    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
#          user_id: user.id)
#  end

  def uploaded_image=(image_field)
    self.name         = base_part_of(image_field.original_filename)
    self.content_type = image_field.content_type.chomp
    # RMagickで画像取得後リサイズしてバイナリ返還後dataセーブ
    img = Magick::Image.from_blob(image_field.read).shift
    img64 = img.resize_to_fit(640,640)
    img30 = img.resize_to_fit(300,300)
    img10 = img.resize_to_fit(100,100)
    binary64 = img64.to_blob  # 画像からバイナリを取得する
    binary30 = img30.to_blob  # 画像からバイナリを取得する
    binary10 = img10.to_blob  # 画像からバイナリを取得する
    self.photo   = binary64
    self.photo_m = binary30
    self.photo_s = binary10
  end

  def base_part_of(file_name)
#    File.basename(file_name).gsub(/[\A\w._-]/, '')
    File.basename(file_name)
  end

end

app/controllers/microposts_controller.rb
# encoding: utf-8

class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :index, :show]
  #before_action :correct_user,   only: :destroy

  def index
    #@microposts = @user.microposts.paginate(page: params[:page])
    @microposts = Micropost.where(user_id: current_user.id).order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def show
    @micropost = Micropost.find(params[:id])
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end
 
  def create
    @micropost = Micropost.new(micropost_params)
    if @micropost.save
      flash[:success] = "一言写真が登録されました!"
      PostMailer.post_email(current_user, @micropost).deliver
      redirect_to root_url
    else
#      @feed_items = []
      flash[:error] = "一言写真は登録できませんでした!"
      redirect_to root_url
#      render 'static_pages/home'
    end
  end

  def destroy
    Micropost.find(params[:id]).destroy
    flash[:success] = "一言写真は削除されました！"
    #@micropost.destroy
    redirect_to root_url
  end

  def download
    @micropost = Micropost.find(params[:micropost_id])
    send_data(@micropost.photo_m,
              filename: @micropost.name,
              type: @micropost.content_type,
              disposition: "inline")
  end

  def download_max
    @micropost = Micropost.find(params[:micropost_id])
    send_data(@micropost.photo,
              filename: @micropost.name,
              type: @micropost.content_type,
              disposition: "inline")
  end

  def download_small
    @micropost = Micropost.find(params[:micropost_id])
    send_data(@micropost.photo_s,
              filename: @micropost.name,
              type: @micropost.content_type,
              disposition: "inline")
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :group_id, :user_id, :uploaded_image)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/views/microposts/_micropost.html.erb
<time datetime="">
  <%= micropost.user.name %>
   | 投稿 <%= time_ago_in_words(micropost.created_at) %>前
  <% if current_user?(micropost.user) || current_user.admin? %>
    | <%= link_to "削除", micropost, method: :delete,
                                 data: { confirm: "本当に削除しますか?" },
                                 title: micropost.content %>
  <% end %>
</time>
<section class="content">
  <% if micropost.name != nil %>
    <p class='cf'>
      <a href="<%= micropost_path(micropost) %>"><img src="<%= micropost_download_small_path(micropost) %>"></a>
      <%= micropost.content %>
    </p>
  <% else %>
    <p class='cf'>
      <%= micropost.content %>
    </p>
  <% end %>
</section>

app/views/microposts/index.html.erb
<% provide(:title, 'マイ一言') %>
<article id="contents">
<header class="head">
<h1>マイ一言</h1>
</header>
<div class="main">
<div id="postArea">
<%= will_paginate @microposts, previous_label: "前ページ", next_label: "次ページ" %>
  <%= render @microposts %>
<%= will_paginate @microposts, previous_label: "前ページ", next_label: "次ページ" %>
</div>
</div>
</article>

app/views/microposts/show.html.erb
<% provide(:title, '一言拡大') %>
<article id="contents">
<header class="head">
<h1><%= @micropost.name %></h1>
</header>
<div class="main">

<div id="pictureArea">
<article>
<section>
<p><img src="<%= micropost_download_max_path(@micropost) %>"/></p>
</section>
</article>
</div>

</div>
</article>