config/routes.rb
E4th::Application.routes.draw do
  resources :users  do
    collection { post :import }
  end

  resources :docs do
    get :download
  end
  
  resources :microposts do
    get :download
    get :download_max
    get :download_small
  end  

  resources :images do
    get :download
    get :download_max
    get :download_small
  end

  resources :articles
  resources :sessions,      only: [:new, :create, :destroy]
  
  root  'static_pages#home'
  match '/find',        to: 'users#find',               via: 'get'
  match '/csv',         to: 'users#csv',                via: 'get'
  match '/signup',      to: 'users#new',                via: 'get'
  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'
  match '/help',        to: 'static_pages#help',        via: 'get'
  match '/about',       to: 'static_pages#about',       via: 'get'

end

app/views/layouts/_footer.html.erb
<footer id="foot">
  <nav>
    <ul>
      <li><%= link_to "ヘルプ", help_path %></li>
      <li><%= link_to "サイト", about_path %></li>
    </ul>
  </nav>
  <section>
    <p>&copy; Akira Kameyama</p>
  </section>
</footer>

app/views/layouts/_header.html.erb
<header id="head">
  <% if signed_in? %>
    <% if content_for(:title) != nil %>
      <% if current_user.group_id == 0 %>
        <h1><%= link_to "NEWS913ホーム", root_path, id: "logo"  %></h1>
      <% elsif current_user.group_id == 1 %>
        <h1><%= link_to "四中ホーム", root_path, id: "logo"  %></h1>
      <% elsif current_user.group_id == 2 then %>
        <h1><%= link_to "高専ホーム", root_path, id: "logo"  %></h1>
      <% elsif current_user.group_id == 3 then %>
        <h1><%= link_to "Ｐ大森ホーム", root_path, id: "logo"  %></h1>
      <% elsif current_user.group_id == 4 then %>
        <h1><%= link_to "亀山ホーム", root_path, id: "logo"  %></h1>
      <% end %>
    <% else %>
      <% if current_user.group_id == 0 %>
        <h1><%= link_to "NEWS913ホーム", root_path, id: "logo_on"  %></h1>
      <% elsif current_user.group_id == 1 %>
        <h1><%= link_to "四中ホーム", root_path, id: "logo_on"  %></h1>
      <% elsif current_user.group_id == 2 then %>
        <h1><%= link_to "高専ホーム", root_path, id: "logo_on"  %></h1>
      <% elsif current_user.group_id == 3 then %>
        <h1><%= link_to "Ｐ大森ホーム", root_path, id: "logo_on"  %></h1>
      <% elsif current_user.group_id == 4 then %>
        <h1><%= link_to "亀山ホーム", root_path, id: "logo_on"  %></h1>
      <% end %>
    <% end %>    
  <% else %>
    <h1><%= link_to "ホーム", root_path, id: "logo_on"  %></h1>
  <% end %>
  <nav>
    <ul>
      <% if signed_in? %>
        <li>
          <% if content_for(:title) == "お知らせ一覧" || 
                content_for(:title) == "お知らせ" || 
                content_for(:title) == "お知らせ更新" %>
            <%= link_to "お知らせ", articles_path, class: "on" %>
          <% else %>
            <%= link_to "お知らせ", articles_path %>
          <% end %>
        </li>
        <li>
          <% if content_for(:title) == "文書一覧" || 
                content_for(:title) == "文書変更" %>
            <%= link_to "文書一覧", docs_path, class: "on" %>
          <% else %>
            <%= link_to "文書一覧", docs_path %>
          <% end %>
        </li>
        <li><%= link_to "サインアウト", signout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "サインイン", signin_path %></li>
      <% end %>
    </ul>
  </nav>

  <% if signed_in? && current_user.family != "GUEST" %>
    <nav>
      <ul>
        <li>
          <% if content_for(:title) == "マイ一言" %>
            <%= link_to "マイ一言", microposts_path, class: "on" %>
          <% else %>
            <%= link_to "マイ一言", microposts_path %>
          <% end %>
        </li>
        <li>
          <% if content_for(:title) == "マイ写真" %>
            <%= link_to "マイ写真", images_path, class: "on" %>
          <% else %>
            <%= link_to "マイ写真", images_path %>
          <% end %>
        </li>
        <li>
          <% if content_for(:title) == "プロフィール" || 
                content_for(:title) == "編集" %>
            <%= link_to "プロフィール", current_user, class: "on" %>
          <% else %>
            <%= link_to "プロフィール", current_user %>
          <% end %>
        </li>
      </ul>
    </nav>
  <% end %>

  <% if signed_in? && current_user.admin? %>
    <nav>
      <ul>
        <li>
          <% if content_for(:title) == "お知らせ登録" %>
            <%= link_to "お知らせ登録", new_article_path, class: "on" %>
          <% else %>
            <%= link_to "お知らせ登録", new_article_path %>
          <% end %>
        </li>
        <li>
          <% if content_for(:title) == "文書登録" %>
            <%= link_to "文書登録", new_doc_path, class: "on" %>
          <% else %>
            <%= link_to "文書登録", new_doc_path %>
          <% end %>
        </li>
        <li>
          <% if content_for(:title) == "全名簿" %>
            <%= link_to "全名簿", users_path, class: "on" %>
          <% else %>
            <%= link_to "全名簿", users_path %>
          <% end %>
        </li>
        <li>
          <% if content_for(:title) == "名簿追加" %>
            <%= link_to "名簿追加", new_user_path, class: "on" %>
          <% else %>
            <%= link_to "名簿追加", new_user_path %>
          <% end %>
        </li>
        <li>
          <%= link_to "SJIS_CSV", csv_path %>
        </li>
      </ul>
    </nav>
  <% end %>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=yes">
    <meta name="Keywords" content="品川区立, 荏原第四中学校, 荏原四中, 同期会, 
                                　1969年卒業, 昭和44年卒業, 都立高専, 10期, 
                                　パイオニア, 大森工場, 生産技術, OB会">
    <meta name="Description" content="同期会、OB会のお知らせサイトです。">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="wrap">
    <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>